services:
  db:
    image: postgres:17.5
    container_name: postgres-db
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1379963147
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/movies
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1379963147
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movie-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  pgdata:
